export const ANALYTICS_CONFIG = {
  BATCH_SIZE: 500,
  QUEUE_NAME: 'analytics-queue',
  WORKER_CONCURRENCY: 5,
  RETRY_ATTEMPTS: 5,
  RETRY_DELAY_MS: 5000, // exponential backoff base
  DASHBOARD_CACHE_TTL_SEC: 60,
  SESSION_ROTATION_HOURS: 24,
  MAX_EVENT_RETENTION_DAYS: 90,
};
