version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    volumes:
      - ./apps/api:/usr/src/app/apps/api
      - ./packages:/usr/src/app/packages
    command: pnpm --filter @hu-partner/api dev
    environment:
      - NODE_ENV=development

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - ./apps/web:/usr/src/app/apps/web
      - ./packages:/usr/src/app/packages
    command: pnpm --filter @hu-partner/web dev
    environment:
      - NODE_ENV=development
